### ISSUE TITLE
Non - eBook reader usage

### ISSUE THREAD

**Issue by Blyzz616** [Ceruleous/EPaperReader#2]
Hi there Ceruleous,

I'm considering using the 7.4" e-ink display to make an information display that's updated one per minute and has some small input capability.

This isn't really an issue, merely a way to try and contact you.

I've never used SPI before and not 100% certain about how it works. Can I push an HTML page to the display automatically or does it need to be in ebook format like epub? Or does it need to be an image?

As this is not an issue, please contact me at an email inbox I've created to receive emails only from you:

ceruleous [at] blyzz.com

Regards,

Jim

**Comment by Ceruleous** [comment]
Hello Blyzz616,

The way our code works is that it renders the epubs into a black and white image and is then processed into raw int data which is pushed to the microcontroller of the SPI.

I guess it works the same for HTML pages because epubs themselves are collections of HTML files within a zip.
